# Generated by Django 4.0.4 on 2022-05-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='reputation',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('storeimage', models.ImageField(upload_to='')),
                ('goods', models.ManyToManyField(through='item.StoreItemRelation', to='item.itemmodel')),
            ],
        ),
        migrations.AddField(
            model_name='storeitemrelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itemmodel'),
        ),
        migrations.AddField(
            model_name='storeitemrelation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.storemodel'),
        ),
    ]
