# Generated by Django 4.0.4 on 2022-05-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_storeitemrelation_remove_itemmodel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='goods',
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='storeimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
