# Generated by Django 4.0.4 on 2022-05-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_storeitemrelation_joined_date_purchasemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='payment_method',
            field=models.CharField(default='cash', max_length=100),
        ),
    ]
