# Generated by Django 4.0.4 on 2022-05-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_purchasemodel_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetailmodel',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.storeitemrelation'),
        ),
    ]
