# Generated by Django 4.0.4 on 2022-05-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_purchasemodel_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetailmodel',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedetailpurchase', to='item.purchasemodel'),
        ),
    ]
