# Generated by Django 4.0.4 on 2022-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_purchasedetailmodel_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetailmodel',
            name='number_of_item',
            field=models.IntegerField(default='1'),
        ),
    ]
